
-- Localize for performance.
local math_random = math.random



function throwing_register_arrow_standard (kind, desc, eq, toughness, craft, craftcount)
	minetest.register_craftitem("throwing:arrow_" .. kind, {
		description = desc .. " Arrow",
		inventory_image = "throwing_arrow_" .. kind .. ".png",
	})
	
	minetest.register_node("throwing:arrow_" .. kind .. "_box", {
		drawtype = "nodebox",
		node_box = {
			type = "fixed",
			fixed = {
				-- Shaft
				{-6.5/17, -1.5/17, -1.5/17, 6.5/17, 1.5/17, 1.5/17},
				--Spitze
				{-4.5/17, 2.5/17, 2.5/17, -3.5/17, -2.5/17, -2.5/17},
				{-8.5/17, 0.5/17, 0.5/17, -6.5/17, -0.5/17, -0.5/17},
				--Federn
				{6.5/17, 1.5/17, 1.5/17, 7.5/17, 2.5/17, 2.5/17},
				{7.5/17, -2.5/17, 2.5/17, 6.5/17, -1.5/17, 1.5/17},
				{7.5/17, 2.5/17, -2.5/17, 6.5/17, 1.5/17, -1.5/17},
				{6.5/17, -1.5/17, -1.5/17, 7.5/17, -2.5/17, -2.5/17},
				
				{7.5/17, 2.5/17, 2.5/17, 8.5/17, 3.5/17, 3.5/17},
				{8.5/17, -3.5/17, 3.5/17, 7.5/17, -2.5/17, 2.5/17},
				{8.5/17, 3.5/17, -3.5/17, 7.5/17, 2.5/17, -2.5/17},
				{7.5/17, -2.5/17, -2.5/17, 8.5/17, -3.5/17, -3.5/17},
			}
		},
		tiles = {"throwing_arrow_" .. kind .. ".png", "throwing_arrow_" .. kind .. ".png", "throwing_arrow_" .. kind .. "_back.png", "throwing_arrow_" .. kind .. "_front.png", "throwing_arrow_" .. kind .. "_2.png", "throwing_arrow_" .. kind .. ".png"},
		groups = {not_in_creative_inventory=1},
	})
	
	local THROWING_ARROW_ENTITY = {
		_name = "throwing:arrow_" .. kind,
		physical = false,
		timer=0,
		visual = "wielditem",
		visual_size = {x=0.1, y=0.1},
		textures = {"throwing:arrow_" .. kind .. "_box"},
		lastpos={},
		collisionbox = {0,0,0,0,0,0},
	}
	
	THROWING_ARROW_ENTITY.on_step = function(self, dtime)
		self.timer=self.timer+dtime
		local pos = self.object:get_pos()
		local node = minetest.get_node(pos)
	
		if self.timer>0.2 then
			local vel = self.object:get_velocity()
			local objs = minetest.get_objects_inside_radius({x=pos.x,y=pos.y,z=pos.z}, 2)
			for k, obj in pairs(objs) do
				if obj:get_luaentity() ~= nil then
					local oname = obj:get_luaentity().name
					if not throwing.entity_blocks_arrow(oname) then
						local speed = vector.length(vel)
						local damage = ((speed + eq)^1.2)/10
            throwing_arrow_punch_entity(obj, self, damage)
						self.object:remove()
					end
        elseif obj:is_player() then
          local speed = vector.length(vel)
          local damage = ((speed + eq)^1.2)/10
          throwing_arrow_punch_entity(obj, self, damage)
          self.object:remove()
        end
			end
		end
	
		if self.lastpos.x~=nil then
			if throwing_node_should_block_arrow(node.name) then
				self.object:remove()
				if math_random() < toughness then
					minetest.add_item(self.lastpos, 'throwing:arrow_' .. kind)
				else
					minetest.add_item(self.lastpos, 'default:stick')
				end
			end
		end
		self.lastpos={x=pos.x, y=pos.y, z=pos.z}
	end
	
	minetest.register_entity("throwing:arrow_" .. kind .. "_entity", THROWING_ARROW_ENTITY)
	
	if not craftcount then
		craftcount = 16
	end

	minetest.register_craft({
		output = 'throwing:arrow_' .. kind .. ' ' .. craftcount,
		recipe = {
			{'default:stick', 'default:stick', craft},
		}
	})
	
	minetest.register_craft({
		output = 'throwing:arrow_' .. kind .. ' ' .. craftcount,
		recipe = {
			{craft, 'default:stick', 'default:stick'},
		}
	})
end

if not DISABLE_STONE_ARROW then
	throwing_register_arrow_standard ('stone', 'Stone', 5, 0.88, 'default:cobble')
end

if not DISABLE_STEEL_ARROW then
	throwing_register_arrow_standard ('steel', 'Steel', 15, 0.94, 'default:steel_ingot')
end

if not DISABLE_DIAMOND_ARROW then
	throwing_register_arrow_standard ('diamond', 'Diamond', 25, 0.97, 'dusts:diamond_shard', 2)
end

if not DISABLE_OBSIDIAN_ARROW then
	throwing_register_arrow_standard ('obsidian', 'Obsidian', 20, 0.88, 'default:obsidian_shard', 2)
end
